sudo: required
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  #this installs google cloud sdk, and then install on instance assigned by travis-CI
  - curl https://sdk.cloud.google.com | bash > /dev/null #read up on how to sdk
  - source $HOME/google-cloud-sdk/path.bash.inc #apply this configuration, set up cloud

  - gcloud components update kubectl #installs and updates kubectl in our environment
  - gcloud auth activate-service-account --key-file service-account.json

