sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  #this installs google cloud sdk, and then install on instance assigned by travis-CI
  - curl https://sdk.cloud.google.com | bash > /dev/null #read up on how to sdk
  - source $HOME/google-cloud-sdk/path.bash.inc #apply this configuration, set up cloud
  - gcloud components update kubectl #installs and updates kubectl in our environment
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-307821 #get REAL project id from google
  - gcloud config set compute/zone us-west1-a #sets zone from google
  - gcloud container clusters get-credentials multi-cluster #get the cluster to work with

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # Logs into Docker Uses environmental variables from Travis dashboard
  - docker build -t sbollman011/react-test -f ./client/Dockerfile.dev ./client #Tests build

script:
  - docker run -e CI=true sbollman011/react-test npm test #run the tests
  
deploy:
  provider: script #We will write our own script
  script: bash ./deploy.sh
  on:
    branch: main


