apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: stephengrider/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST #from redis clusterIP 
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'  #from redis clusterIP
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service #from postgres clusterIP    
            - name: PGPORT
              value: '5432' #from postgres clusterIP
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD #Environment variable, NOT the secret
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD

